### ISSUE TITLE
[FEATURE] - Support basic regular expressions!

### ISSUE THREAD

**Issue by evilmega** [Gael-Lopes-Da-Silva/TodoedVSCode#1]
**Description**

Your extension is so close to matching my requirements... I would like to be able to configure a keyword such as: "BUG-\d+", which would highlight:

e.g.

  BUG-1
  BUG-203
  BUG-99999
  ...etc.

- Ideally it should work with other keywords, so I could do:

   " // TODO(BUG-1234): The TODO would be highlighted in one color, and the BUG would be highlighted in a different color. "

**Comment by Gael-Lopes-Da-Silva** [comment]
Even if it's a bit late, it should be good now.
